# Generated by Django 5.2.6 on 2025-11-01 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_signupuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignupUser',
        ),
    ]
