# Generated by Django 5.2.6 on 2025-11-01 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_user_regestration'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User_regestration',
            new_name='UserRegestration',
        ),
    ]
