# Generated by Django 5.2.6 on 2025-11-01 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_userprofile_delete_userregestration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('height', models.CharField(max_length=50)),
                ('primary_goal', models.CharField(choices=[('Weight Loss', 'Weight Loss'), ('Weight Gain', 'Weight Gain'), ('Muscle Gain', 'Muscle Gain'), ('Healthy Lifestyle', 'Healthy Lifestyle')], max_length=50)),
                ('diet_type', models.CharField(choices=[('Veg', 'Veg'), ('Non-Veg', 'Non-Veg'), ('Vegan', 'Vegan'), ('Keto', 'Keto'), ('Other', 'Other')], max_length=50)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
