# Generated by Django 5.2.6 on 2025-11-10 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_inquiry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inquiry',
        ),
    ]
